added encoding presets and license
ATofighi/skyroom-record pull request #7
Opened 2021-03-05 07:17 UTC by sfmth

I added 3 encoding presets and defaulted it to no encoding as the original webm file is quite good and for long recordings there could be a huge time spent on encoding plus some loss in quality. It's Friday and I couldn't fully test it, you might want to do that.

2021-03-05 23:59 UTC, ATofighi requested changes
Thanks for you contribution. 

Looks good to me.

I only suggest a change that reuses `ffmpeg.input(donwloaded_file)` and doesn't repeat it.

+ fix flake8 issue that occur for too many new lines at line 384 and 385.  [https://travis-ci.com/github/ATofighi/skyroom-record/builds/219153531](url).

2021-03-05 23:59 UTC, ATofighi commented on src/main.py
> +    if args.encoding == "quality-optimized":
```suggestion
    ffmpeg_pipe = ffmpeg.input(new_webm_file)
    if args.encoding == "quality-optimized":
```

2021-03-05 23:59 UTC, ATofighi commented on src/main.py
> +        ffmpeg.input(new_webm_file).output(
```suggestion
        ffmpeg_pipe.output(
```

2021-03-05 23:59 UTC, ATofighi commented on src/main.py
> +        ffmpeg.input(new_webm_file).output(
```suggestion
        ffmpeg_pipe.output(
```

2021-03-05 23:59 UTC, ATofighi commented on src/main.py
> +        ffmpeg.input('video.webm').output(
```suggestion
        ffmpeg_pipe.output(
```

2021-03-06 00:01 UTC, ATofighi commented
Fixes #6 #5 #3

2021-03-06 05:17 UTC, sfmth commented
Alright all set I guess

2021-03-06 08:56 UTC, ATofighi approved these changes

2021-03-06 08:56 UTC, merged